/*
My Data My Consent - Developer API

Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: v1
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
)

// ConsentRequestReceiver Consent request receiver details
type ConsentRequestReceiver struct {
	// Consent request receiver identifiers
	Identifiers []StringStringKeyValuePair `json:"identifiers,omitempty"`
	IdentificationStrategy *IdentificationStrategy `json:"identificationStrategy,omitempty"`
}

// NewConsentRequestReceiver instantiates a new ConsentRequestReceiver object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsentRequestReceiver() *ConsentRequestReceiver {
	this := ConsentRequestReceiver{}
	return &this
}

// NewConsentRequestReceiverWithDefaults instantiates a new ConsentRequestReceiver object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsentRequestReceiverWithDefaults() *ConsentRequestReceiver {
	this := ConsentRequestReceiver{}
	return &this
}

// GetIdentifiers returns the Identifiers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConsentRequestReceiver) GetIdentifiers() []StringStringKeyValuePair {
	if o == nil  {
		var ret []StringStringKeyValuePair
		return ret
	}
	return o.Identifiers
}

// GetIdentifiersOk returns a tuple with the Identifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConsentRequestReceiver) GetIdentifiersOk() ([]StringStringKeyValuePair, bool) {
	if o == nil || o.Identifiers == nil {
		return nil, false
	}
	return o.Identifiers, true
}

// HasIdentifiers returns a boolean if a field has been set.
func (o *ConsentRequestReceiver) HasIdentifiers() bool {
	if o != nil && o.Identifiers != nil {
		return true
	}

	return false
}

// SetIdentifiers gets a reference to the given []StringStringKeyValuePair and assigns it to the Identifiers field.
func (o *ConsentRequestReceiver) SetIdentifiers(v []StringStringKeyValuePair) {
	o.Identifiers = v
}

// GetIdentificationStrategy returns the IdentificationStrategy field value if set, zero value otherwise.
func (o *ConsentRequestReceiver) GetIdentificationStrategy() IdentificationStrategy {
	if o == nil || o.IdentificationStrategy == nil {
		var ret IdentificationStrategy
		return ret
	}
	return *o.IdentificationStrategy
}

// GetIdentificationStrategyOk returns a tuple with the IdentificationStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsentRequestReceiver) GetIdentificationStrategyOk() (*IdentificationStrategy, bool) {
	if o == nil || o.IdentificationStrategy == nil {
		return nil, false
	}
	return o.IdentificationStrategy, true
}

// HasIdentificationStrategy returns a boolean if a field has been set.
func (o *ConsentRequestReceiver) HasIdentificationStrategy() bool {
	if o != nil && o.IdentificationStrategy != nil {
		return true
	}

	return false
}

// SetIdentificationStrategy gets a reference to the given IdentificationStrategy and assigns it to the IdentificationStrategy field.
func (o *ConsentRequestReceiver) SetIdentificationStrategy(v IdentificationStrategy) {
	o.IdentificationStrategy = &v
}

func (o ConsentRequestReceiver) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Identifiers != nil {
		toSerialize["identifiers"] = o.Identifiers
	}
	if o.IdentificationStrategy != nil {
		toSerialize["identificationStrategy"] = o.IdentificationStrategy
	}
	return json.Marshal(toSerialize)
}

type NullableConsentRequestReceiver struct {
	value *ConsentRequestReceiver
	isSet bool
}

func (v NullableConsentRequestReceiver) Get() *ConsentRequestReceiver {
	return v.value
}

func (v *NullableConsentRequestReceiver) Set(val *ConsentRequestReceiver) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentRequestReceiver) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentRequestReceiver) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentRequestReceiver(val *ConsentRequestReceiver) *NullableConsentRequestReceiver {
	return &NullableConsentRequestReceiver{value: val, isSet: true}
}

func (v NullableConsentRequestReceiver) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentRequestReceiver) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


