/*
My Data My Consent - Developer API

Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: v1
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
)

// DataConsentDocumentIssuer Data Consent document issuer details.
type DataConsentDocumentIssuer struct {
	// Document issuer id.
	Id string `json:"id"`
	// Document issuer name.
	Name string `json:"name"`
}

// NewDataConsentDocumentIssuer instantiates a new DataConsentDocumentIssuer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataConsentDocumentIssuer(id string, name string) *DataConsentDocumentIssuer {
	this := DataConsentDocumentIssuer{}
	this.Id = id
	this.Name = name
	return &this
}

// NewDataConsentDocumentIssuerWithDefaults instantiates a new DataConsentDocumentIssuer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataConsentDocumentIssuerWithDefaults() *DataConsentDocumentIssuer {
	this := DataConsentDocumentIssuer{}
	return &this
}

// GetId returns the Id field value
func (o *DataConsentDocumentIssuer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataConsentDocumentIssuer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataConsentDocumentIssuer) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataConsentDocumentIssuer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataConsentDocumentIssuer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataConsentDocumentIssuer) SetName(v string) {
	o.Name = v
}

func (o DataConsentDocumentIssuer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableDataConsentDocumentIssuer struct {
	value *DataConsentDocumentIssuer
	isSet bool
}

func (v NullableDataConsentDocumentIssuer) Get() *DataConsentDocumentIssuer {
	return v.value
}

func (v *NullableDataConsentDocumentIssuer) Set(val *DataConsentDocumentIssuer) {
	v.value = val
	v.isSet = true
}

func (v NullableDataConsentDocumentIssuer) IsSet() bool {
	return v.isSet
}

func (v *NullableDataConsentDocumentIssuer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataConsentDocumentIssuer(val *DataConsentDocumentIssuer) *NullableDataConsentDocumentIssuer {
	return &NullableDataConsentDocumentIssuer{value: val, isSet: true}
}

func (v NullableDataConsentDocumentIssuer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataConsentDocumentIssuer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


