/*
My Data My Consent - Developer API

Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: 1.0
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
)

// Aif struct for Aif
type Aif struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Identifier string `json:"identifier"`
	Amount float64 `json:"amount"`
}

// NewAif instantiates a new Aif object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAif(id string, name string, identifier string, amount float64) *Aif {
	this := Aif{}
	this.Id = id
	this.Name = name
	this.Identifier = identifier
	this.Amount = amount
	return &this
}

// NewAifWithDefaults instantiates a new Aif object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAifWithDefaults() *Aif {
	this := Aif{}
	return &this
}

// GetId returns the Id field value
func (o *Aif) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Aif) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Aif) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Aif) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Aif) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Aif) SetName(v string) {
	o.Name = v
}

// GetIdentifier returns the Identifier field value
func (o *Aif) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *Aif) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *Aif) SetIdentifier(v string) {
	o.Identifier = v
}

// GetAmount returns the Amount field value
func (o *Aif) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Aif) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Aif) SetAmount(v float64) {
	o.Amount = v
}

func (o Aif) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["identifier"] = o.Identifier
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableAif struct {
	value *Aif
	isSet bool
}

func (v NullableAif) Get() *Aif {
	return v.value
}

func (v *NullableAif) Set(val *Aif) {
	v.value = val
	v.isSet = true
}

func (v NullableAif) IsSet() bool {
	return v.isSet
}

func (v *NullableAif) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAif(val *Aif) *NullableAif {
	return &NullableAif{value: val, isSet: true}
}

func (v NullableAif) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAif) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


