/*
My Data My Consent - Developer API

Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: 1.0
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
)

// BillPaymentTransaction struct for BillPaymentTransaction
type BillPaymentTransaction struct {
	Id string `json:"id"`
}

// NewBillPaymentTransaction instantiates a new BillPaymentTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillPaymentTransaction(id string) *BillPaymentTransaction {
	this := BillPaymentTransaction{}
	this.Id = id
	return &this
}

// NewBillPaymentTransactionWithDefaults instantiates a new BillPaymentTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillPaymentTransactionWithDefaults() *BillPaymentTransaction {
	this := BillPaymentTransaction{}
	return &this
}

// GetId returns the Id field value
func (o *BillPaymentTransaction) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BillPaymentTransaction) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BillPaymentTransaction) SetId(v string) {
	o.Id = v
}

func (o BillPaymentTransaction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableBillPaymentTransaction struct {
	value *BillPaymentTransaction
	isSet bool
}

func (v NullableBillPaymentTransaction) Get() *BillPaymentTransaction {
	return v.value
}

func (v *NullableBillPaymentTransaction) Set(val *BillPaymentTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableBillPaymentTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableBillPaymentTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillPaymentTransaction(val *BillPaymentTransaction) *NullableBillPaymentTransaction {
	return &NullableBillPaymentTransaction{value: val, isSet: true}
}

func (v NullableBillPaymentTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillPaymentTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


