/*
My Data My Consent - Developer API

Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: 1.0
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
)

// FinancialAccountEquityTransactionAllOf struct for FinancialAccountEquityTransactionAllOf
type FinancialAccountEquityTransactionAllOf struct {
	Type string `json:"type"`
}

// NewFinancialAccountEquityTransactionAllOf instantiates a new FinancialAccountEquityTransactionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialAccountEquityTransactionAllOf(type_ string) *FinancialAccountEquityTransactionAllOf {
	this := FinancialAccountEquityTransactionAllOf{}
	this.Type = type_
	return &this
}

// NewFinancialAccountEquityTransactionAllOfWithDefaults instantiates a new FinancialAccountEquityTransactionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialAccountEquityTransactionAllOfWithDefaults() *FinancialAccountEquityTransactionAllOf {
	this := FinancialAccountEquityTransactionAllOf{}
	return &this
}

// GetType returns the Type field value
func (o *FinancialAccountEquityTransactionAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FinancialAccountEquityTransactionAllOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FinancialAccountEquityTransactionAllOf) SetType(v string) {
	o.Type = v
}

func (o FinancialAccountEquityTransactionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableFinancialAccountEquityTransactionAllOf struct {
	value *FinancialAccountEquityTransactionAllOf
	isSet bool
}

func (v NullableFinancialAccountEquityTransactionAllOf) Get() *FinancialAccountEquityTransactionAllOf {
	return v.value
}

func (v *NullableFinancialAccountEquityTransactionAllOf) Set(val *FinancialAccountEquityTransactionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialAccountEquityTransactionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialAccountEquityTransactionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialAccountEquityTransactionAllOf(val *FinancialAccountEquityTransactionAllOf) *NullableFinancialAccountEquityTransactionAllOf {
	return &NullableFinancialAccountEquityTransactionAllOf{value: val, isSet: true}
}

func (v NullableFinancialAccountEquityTransactionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialAccountEquityTransactionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


