/*
My Data My Consent - Developer API

Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: 1.0
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
	"time"
)

// TermDepositTransaction struct for TermDepositTransaction
type TermDepositTransaction struct {
	Id string `json:"id"`
	Amount float64 `json:"amount"`
	CurrencyCode string `json:"currency_code"`
	Narration string `json:"narration"`
	TxnType TermDepositTransactionType `json:"txn_type"`
	Mode TermDepositTransactionMode `json:"mode"`
	TransactedAtUtc time.Time `json:"transacted_at_utc"`
}

// NewTermDepositTransaction instantiates a new TermDepositTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTermDepositTransaction(id string, amount float64, currencyCode string, narration string, txnType TermDepositTransactionType, mode TermDepositTransactionMode, transactedAtUtc time.Time) *TermDepositTransaction {
	this := TermDepositTransaction{}
	this.Id = id
	this.Amount = amount
	this.CurrencyCode = currencyCode
	this.Narration = narration
	this.TxnType = txnType
	this.Mode = mode
	this.TransactedAtUtc = transactedAtUtc
	return &this
}

// NewTermDepositTransactionWithDefaults instantiates a new TermDepositTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTermDepositTransactionWithDefaults() *TermDepositTransaction {
	this := TermDepositTransaction{}
	return &this
}

// GetId returns the Id field value
func (o *TermDepositTransaction) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TermDepositTransaction) SetId(v string) {
	o.Id = v
}

// GetAmount returns the Amount field value
func (o *TermDepositTransaction) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TermDepositTransaction) SetAmount(v float64) {
	o.Amount = v
}

// GetCurrencyCode returns the CurrencyCode field value
func (o *TermDepositTransaction) GetCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyCode, true
}

// SetCurrencyCode sets field value
func (o *TermDepositTransaction) SetCurrencyCode(v string) {
	o.CurrencyCode = v
}

// GetNarration returns the Narration field value
func (o *TermDepositTransaction) GetNarration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Narration
}

// GetNarrationOk returns a tuple with the Narration field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetNarrationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Narration, true
}

// SetNarration sets field value
func (o *TermDepositTransaction) SetNarration(v string) {
	o.Narration = v
}

// GetTxnType returns the TxnType field value
func (o *TermDepositTransaction) GetTxnType() TermDepositTransactionType {
	if o == nil {
		var ret TermDepositTransactionType
		return ret
	}

	return o.TxnType
}

// GetTxnTypeOk returns a tuple with the TxnType field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetTxnTypeOk() (*TermDepositTransactionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxnType, true
}

// SetTxnType sets field value
func (o *TermDepositTransaction) SetTxnType(v TermDepositTransactionType) {
	o.TxnType = v
}

// GetMode returns the Mode field value
func (o *TermDepositTransaction) GetMode() TermDepositTransactionMode {
	if o == nil {
		var ret TermDepositTransactionMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetModeOk() (*TermDepositTransactionMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *TermDepositTransaction) SetMode(v TermDepositTransactionMode) {
	o.Mode = v
}

// GetTransactedAtUtc returns the TransactedAtUtc field value
func (o *TermDepositTransaction) GetTransactedAtUtc() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.TransactedAtUtc
}

// GetTransactedAtUtcOk returns a tuple with the TransactedAtUtc field value
// and a boolean to check if the value has been set.
func (o *TermDepositTransaction) GetTransactedAtUtcOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactedAtUtc, true
}

// SetTransactedAtUtc sets field value
func (o *TermDepositTransaction) SetTransactedAtUtc(v time.Time) {
	o.TransactedAtUtc = v
}

func (o TermDepositTransaction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["currency_code"] = o.CurrencyCode
	}
	if true {
		toSerialize["narration"] = o.Narration
	}
	if true {
		toSerialize["txn_type"] = o.TxnType
	}
	if true {
		toSerialize["mode"] = o.Mode
	}
	if true {
		toSerialize["transacted_at_utc"] = o.TransactedAtUtc
	}
	return json.Marshal(toSerialize)
}

type NullableTermDepositTransaction struct {
	value *TermDepositTransaction
	isSet bool
}

func (v NullableTermDepositTransaction) Get() *TermDepositTransaction {
	return v.value
}

func (v *NullableTermDepositTransaction) Set(val *TermDepositTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTermDepositTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTermDepositTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTermDepositTransaction(val *TermDepositTransaction) *NullableTermDepositTransaction {
	return &NullableTermDepositTransaction{value: val, isSet: true}
}

func (v NullableTermDepositTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTermDepositTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


