/*
My Data My Consent - Developer API

Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

API version: v1
Contact: support@mydatamyconsent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/mydatamyconsent/sdk

import (
	"encoding/json"
)

// UriDetails struct for UriDetails
type UriDetails struct {
	Aadhaar string `json:"aadhaar"`
	Uri string `json:"uri"`
	DocType string `json:"docType"`
	DocName string `json:"docName"`
	DocId string `json:"docId"`
	IssuedOn string `json:"issuedOn"`
	ValidFrom string `json:"validFrom"`
	ValidTo NullableString `json:"validTo,omitempty"`
	Timestamp NullableString `json:"timestamp,omitempty"`
	Action NullableString `json:"action,omitempty"`
}

// NewUriDetails instantiates a new UriDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUriDetails(aadhaar string, uri string, docType string, docName string, docId string, issuedOn string, validFrom string) *UriDetails {
	this := UriDetails{}
	this.Aadhaar = aadhaar
	this.Uri = uri
	this.DocType = docType
	this.DocName = docName
	this.DocId = docId
	this.IssuedOn = issuedOn
	this.ValidFrom = validFrom
	return &this
}

// NewUriDetailsWithDefaults instantiates a new UriDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUriDetailsWithDefaults() *UriDetails {
	this := UriDetails{}
	return &this
}

// GetAadhaar returns the Aadhaar field value
func (o *UriDetails) GetAadhaar() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Aadhaar
}

// GetAadhaarOk returns a tuple with the Aadhaar field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetAadhaarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aadhaar, true
}

// SetAadhaar sets field value
func (o *UriDetails) SetAadhaar(v string) {
	o.Aadhaar = v
}

// GetUri returns the Uri field value
func (o *UriDetails) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *UriDetails) SetUri(v string) {
	o.Uri = v
}

// GetDocType returns the DocType field value
func (o *UriDetails) GetDocType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocType
}

// GetDocTypeOk returns a tuple with the DocType field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetDocTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocType, true
}

// SetDocType sets field value
func (o *UriDetails) SetDocType(v string) {
	o.DocType = v
}

// GetDocName returns the DocName field value
func (o *UriDetails) GetDocName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocName
}

// GetDocNameOk returns a tuple with the DocName field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetDocNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocName, true
}

// SetDocName sets field value
func (o *UriDetails) SetDocName(v string) {
	o.DocName = v
}

// GetDocId returns the DocId field value
func (o *UriDetails) GetDocId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocId
}

// GetDocIdOk returns a tuple with the DocId field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetDocIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocId, true
}

// SetDocId sets field value
func (o *UriDetails) SetDocId(v string) {
	o.DocId = v
}

// GetIssuedOn returns the IssuedOn field value
func (o *UriDetails) GetIssuedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuedOn
}

// GetIssuedOnOk returns a tuple with the IssuedOn field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetIssuedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuedOn, true
}

// SetIssuedOn sets field value
func (o *UriDetails) SetIssuedOn(v string) {
	o.IssuedOn = v
}

// GetValidFrom returns the ValidFrom field value
func (o *UriDetails) GetValidFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value
// and a boolean to check if the value has been set.
func (o *UriDetails) GetValidFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidFrom, true
}

// SetValidFrom sets field value
func (o *UriDetails) SetValidFrom(v string) {
	o.ValidFrom = v
}

// GetValidTo returns the ValidTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UriDetails) GetValidTo() string {
	if o == nil || o.ValidTo.Get() == nil {
		var ret string
		return ret
	}
	return *o.ValidTo.Get()
}

// GetValidToOk returns a tuple with the ValidTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UriDetails) GetValidToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidTo.Get(), o.ValidTo.IsSet()
}

// HasValidTo returns a boolean if a field has been set.
func (o *UriDetails) HasValidTo() bool {
	if o != nil && o.ValidTo.IsSet() {
		return true
	}

	return false
}

// SetValidTo gets a reference to the given NullableString and assigns it to the ValidTo field.
func (o *UriDetails) SetValidTo(v string) {
	o.ValidTo.Set(&v)
}
// SetValidToNil sets the value for ValidTo to be an explicit nil
func (o *UriDetails) SetValidToNil() {
	o.ValidTo.Set(nil)
}

// UnsetValidTo ensures that no value is present for ValidTo, not even an explicit nil
func (o *UriDetails) UnsetValidTo() {
	o.ValidTo.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UriDetails) GetTimestamp() string {
	if o == nil || o.Timestamp.Get() == nil {
		var ret string
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UriDetails) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *UriDetails) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableString and assigns it to the Timestamp field.
func (o *UriDetails) SetTimestamp(v string) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *UriDetails) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *UriDetails) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetAction returns the Action field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UriDetails) GetAction() string {
	if o == nil || o.Action.Get() == nil {
		var ret string
		return ret
	}
	return *o.Action.Get()
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UriDetails) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Action.Get(), o.Action.IsSet()
}

// HasAction returns a boolean if a field has been set.
func (o *UriDetails) HasAction() bool {
	if o != nil && o.Action.IsSet() {
		return true
	}

	return false
}

// SetAction gets a reference to the given NullableString and assigns it to the Action field.
func (o *UriDetails) SetAction(v string) {
	o.Action.Set(&v)
}
// SetActionNil sets the value for Action to be an explicit nil
func (o *UriDetails) SetActionNil() {
	o.Action.Set(nil)
}

// UnsetAction ensures that no value is present for Action, not even an explicit nil
func (o *UriDetails) UnsetAction() {
	o.Action.Unset()
}

func (o UriDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["aadhaar"] = o.Aadhaar
	}
	if true {
		toSerialize["uri"] = o.Uri
	}
	if true {
		toSerialize["docType"] = o.DocType
	}
	if true {
		toSerialize["docName"] = o.DocName
	}
	if true {
		toSerialize["docId"] = o.DocId
	}
	if true {
		toSerialize["issuedOn"] = o.IssuedOn
	}
	if true {
		toSerialize["validFrom"] = o.ValidFrom
	}
	if o.ValidTo.IsSet() {
		toSerialize["validTo"] = o.ValidTo.Get()
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.Action.IsSet() {
		toSerialize["action"] = o.Action.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableUriDetails struct {
	value *UriDetails
	isSet bool
}

func (v NullableUriDetails) Get() *UriDetails {
	return v.value
}

func (v *NullableUriDetails) Set(val *UriDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableUriDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableUriDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUriDetails(val *UriDetails) *NullableUriDetails {
	return &NullableUriDetails{value: val, isSet: true}
}

func (v NullableUriDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUriDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


